const About = () => {

    return (
        <div style={{width: '90%', textAlign:'center', margin: '1rem'}}>
            <h1>Lorem ipsum dolor</h1>
            <p style={{fontSize:'1.5rem'}}>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Exercitationem amet ex, debitis fugiat aut facilis dicta excepturi odio consectetur blanditiis praesentium perspiciatis quidem nostrum natus numquam quaerat. Veniam dignissimos libero officiis odio unde culpa consequuntur sed! Consequatur eaque eos velit odio ex ab aperiam nam accusamus vel autem provident, repellendus molestiae tempore temporibus vero! Nemo iusto eveniet suscipit ex reiciendis, et cum laborum laboriosam sunt voluptate non ducimus doloribus expedita, quaerat cupiditate reprehenderit dolorum illo voluptas. Obcaecati quo nulla aperiam impedit earum eaque sit ad? Tempora ad voluptatem esse temporibus deleniti commodi magnam minus ipsam provident, dolorum, quos ipsa officia eligendi fugiat ducimus neque eos voluptatibus natus rem maiores illo dicta rerum est. Exercitationem eveniet quae nam omnis repellendus animi iusto, delectus accusamus a voluptate corrupti, molestiae cumque atque ratione tempore dolores, sapiente aperiam nisi cum minus quibusdam vel rerum natus beatae. Inventore voluptates, adipisci dicta earum animi ex aut asperiores ea omnis eveniet ullam ipsam est molestias autem quia dolore ipsum cupiditate ad assumenda rem provident vero! Incidunt quasi tenetur nemo possimus libero quam laudantium, temporibus, sed, recusandae ducimus modi perferendis aliquam! Optio necessitatibus aperiam nostrum, modi et non earum odit tempore mollitia voluptate minima laborum pariatur dolor a ex molestias deserunt aliquid dignissimos officiis fugiat, fugit illo consequatur ullam sed! Nisi provident culpa, cum vero libero rem eius, similique nesciunt velit, ad error laudantium aspernatur dolorem nihil consequuntur voluptatem natus eveniet maxime. Ea corporis et repellat, eveniet deleniti ipsa nostrum placeat quod dicta quidem laboriosam laborum numquam iste?</p>
            <h1>Lorem ipsum dolor sit amet consectetur adipisicing elit. </h1>
            <p style={{fontSize:'1.2rem'}}>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Numquam necessitatibus omnis labore, aspernatur, modi facilis provident maiores dolorem, culpa obcaecati veritatis impedit et tempore deleniti fugit a tenetur aperiam sapiente eum? Dolorem earum necessitatibus quia debitis autem neque at! Cum recusandae distinctio excepturi nostrum nisi nulla nobis ad doloribus pariatur cumque animi iure perspiciatis, quia aut enim voluptas iusto ipsa officiis saepe obcaecati. Veritatis debitis obcaecati, eos sed, consequuntur vero accusamus neque ea, libero animi eveniet. Hic facere cupiditate omnis explicabo pariatur excepturi, error culpa voluptatem et architecto. Quasi saepe delectus eos in, molestias illo ad est maxime! Blanditiis quas architecto a obcaecati fuga necessitatibus quaerat veniam repudiandae culpa libero. Nobis numquam et culpa ullam voluptate pariatur quis dolorum accusantium quae dolores animi quas rerum optio, saepe quam natus. Dolor perferendis explicabo, vitae veritatis placeat pariatur id consectetur soluta cupiditate amet facere esse hic odit exercitationem, cum recusandae molestias fugit in et. Consectetur, facilis a accusamus praesentium blanditiis consequatur officia laboriosam neque iure doloremque. Quas dolores tempora ab alias. Ullam quos fugit corporis a enim aperiam animi libero voluptatem perferendis nemo quis explicabo dolorum velit magni, temporibus dicta accusantium debitis. Blanditiis iure temporibus, consequuntur odio explicabo deleniti mollitia autem debitis.</p>
        </div>
    )
};

export default About;